server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: motica99

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
#        one-indexed-parameters: true
        default-page-size: 5