### 회원가입
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "email": "lucaschoi@gmail.com",
  "password": "asdf",
  "name:": "minsoo choi"
}

### 로그인
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "lucaschoi@gmail.com",
  "password": "asdf"
}

### 인증이 필요한 페이지 요청
GET {{baseUrl}}/foo
Content-Type: application/json
Cookie: SESSION=b04b8617-a910-4613-8cde-f7b4ecbecc51

