### 회원가입
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "email": "lucaschoi@gmail.com",
  "password": "asdf",
  "name:": "minsoo choi"
}

### 로그인
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=choi&password=1234

