### 로그인

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "lucaschoi@gmail.com",
  "password": "asdf"
}

### 인증 페이지 요청
GET {{baseUrl}}/foo
Content-Type: application/json
Cookie: SESSION=f0c940be-d5d3-4e26-ba5e-0b2b29774a57

